### ISSUE TITLE
Twitter API secrets should not be stored in code.

### ISSUE THREAD

**Issue by techmantonio** [howard-university-web-services/howard_paragraphs#2]
This is the file (lines 83-86):
https://github.com/howard-university-web-services/howard_paragraphs/blob/8.x-1.x/modules/hp_twitter_feed/hp_twitter_feed.module

**Comment by drogers98** [comment]
This was for 2 reasons:

- This was a private repo so it didn't matter much, and we need it across multi-sites. Otherwise it would need to be inputed to every sub-site that needed it, so that it was in either config or content in the DB.
- If an update is needed, we don't want to have to manually change it in the DB/configs everywhere it appears.

I do agree this is not best practice, and happy to discuss alternatives. I do however want to keep in mind future updates/etc as we do. I think this kind of slipped our radar when trying to make it available to all installs via a public repo.

Please let me know if you have any suggestions!

Cheers,

Dan

**Comment by drogers98** [comment]
complete, moved to config.
